version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: health_tracker_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_USERNAME: root
      DB_PASSWORD: root_password
      DB_NAME: health_tracker_dev
      DB_HOST: mysql_db
      JWT_SECRET: your_jwt_secret_key # IMPORTANT: Change this in production!
    depends_on:
      - mysql_db
    restart: unless-stopped

  ml_microservice:
    build: ./ml-microservice
    container_name: ml_microservice
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:


