'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import Sidebar from './Sidebar';
import { Menu, Bell, Settings, User, Search } from 'lucide-react';
const DashboardLayout = ({ children }) => {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const toggleSidebar = () => {
        setSidebarOpen(!sidebarOpen);
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-50 dark:bg-gray-900 flex", children: [_jsx(Sidebar, { isOpen: sidebarOpen, onToggle: toggleSidebar }), _jsxs("div", { className: "flex-1 flex flex-col lg:ml-0", children: [_jsx("header", { className: "bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-4 py-4 lg:px-6 sticky top-0 z-30", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { onClick: toggleSidebar, className: "lg:hidden p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors", children: _jsx(Menu, { className: "w-5 h-5" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: "Health Dashboard" }), _jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Welcome back, John!" })] })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "hidden md:flex items-center space-x-2", children: _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" }), _jsx("input", { type: "text", placeholder: "Search...", className: "pl-10 pr-4 py-2 border border-gray-200 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent" })] }) }), _jsxs("button", { className: "p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors relative", children: [_jsx(Bell, { className: "w-5 h-5 text-gray-600 dark:text-gray-400" }), _jsx("span", { className: "absolute -top-1 -right-1 w-3 h-3 bg-red-500 rounded-full" })] }), _jsx("button", { className: "p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors", children: _jsx(Settings, { className: "w-5 h-5 text-gray-600 dark:text-gray-400" }) }), _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center", children: _jsx(User, { className: "w-4 h-4 text-white" }) }), _jsxs("div", { className: "hidden sm:block", children: [_jsx("p", { className: "text-sm font-medium text-gray-900 dark:text-white", children: "John Doe" }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: "Health Enthusiast" })] })] })] })] }) }), _jsx("main", { className: "flex-1 p-4 lg:p-6 overflow-auto", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsx("div", { className: "animate-fade-in-up", children: children }) }) })] })] }));
};
export default DashboardLayout;
